//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalVisionPioneer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string patientEmail { get; set; }
        public string patientPwd { get; set; }
        public int patientId { get; set; }
    }
}
