//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalVisionPioneer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class docInfo
    {
        public int docId { get; set; }
        public string docName { get; set; }
        public string docMajor { get; set; }
        public bool docAppointment { get; set; }
    }
}
