//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalVisionPioneer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalVisionPioneerEntities : DbContext
    {
        public MedicalVisionPioneerEntities()
            : base("name=MedicalVisionPioneerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PatientInfo> PatientInfo { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<HWinfo> HWinfo { get; set; }
        public virtual DbSet<docAccount> docAccount { get; set; }
        public virtual DbSet<docInfo> docInfo { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<openAppointment> openAppointment { get; set; }
    }
}
