//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalVisionPioneer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public string patientName { get; set; }
        public Nullable<byte> patientAge { get; set; }
        public string patientSex { get; set; }
        public Nullable<System.DateTime> patientBirthday { get; set; }
        public string patientEmail { get; set; }
        public string patientPhone { get; set; }
        public Nullable<int> patientHeight { get; set; }
        public Nullable<int> patientWeight { get; set; }
        public int AccountID { get; set; }
        public int id { get; set; }
        public string patientNickname { get; set; }
    }
}
